module.exports = {
  emptyEmail: { message: '"email" is not allowed to be empty' },
  emptyPassword: { message: '"password" is not allowed to be empty' },
  invalidEmail: { message: '"email" must be a valid email' },
  invalidFields: { message: 'Invalid fields' },
  invalidToken: { message: 'Expired or invalid token' },
  noEmail: { message: '"email" is required' },
  noName: { message: '"name" is required' },
  noPassword: { message: '"password" is required' },
  noToken: { message: 'Token not found' },
  shortDisplayName: { message: '"displayName" length must be at least 8 characters long' },
  shortPassword: { message: '"password" length must be 6 characters long' },
  userNotExist: { message: 'User does not exist' },
  userRegistered: { message: 'User already registered' },
  noContent: { message: '"content" is required' },
  noCategoryIds: { message: '"categoryIds" is required' },
  noTitle: { message: '"title" is required' },
  categoryIdNotFound: { message: '"categoryIds" not found' },
  postNotFound: { message: 'Post does not exist' },
  unauthorizedUser: { message: 'Unauthorized user' },
  categoriesCannotBeEdited: { message: 'Categories cannot be edited' },
};
